# Generated by Django 5.1.8 on 2025-05-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0004_remove_rappel_cotisations_membre__73b8d7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RappelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('nom', models.CharField(help_text='Nom descriptif pour identifier le template', max_length=100, verbose_name='Nom du template')),
                ('type_template', models.CharField(choices=[('standard', 'Standard'), ('urgent', 'Urgent'), ('formal', 'Formel/Mise en demeure'), ('custom', 'Personnalisé')], default='standard', max_length=20, verbose_name='Type de template')),
                ('type_rappel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('courrier', 'Courrier'), ('appel', 'Appel téléphonique')], default='email', help_text='Pour quel mode de communication ce template est destiné', max_length=20, verbose_name='Type de rappel')),
                ('sujet', models.CharField(blank=True, help_text='Sujet du message (pour emails principalement)', max_length=200, verbose_name='Sujet')),
                ('contenu', models.TextField(help_text='Variables disponibles: {prenom}, {nom}, {reference}, {montant}, {date_echeance}, {date_limite}, {jours_retard}, {association_nom}', verbose_name='Contenu du template')),
                ('langue', models.CharField(default='fr', help_text='Code langue (fr, en, etc.)', max_length=5, verbose_name='Langue')),
                ('actif', models.BooleanField(default=True, help_text='Template disponible pour utilisation', verbose_name='Actif')),
                ('niveau_min', models.PositiveIntegerField(default=1, help_text='Niveau de rappel minimum pour utiliser ce template', verbose_name='Niveau minimum')),
                ('niveau_max', models.PositiveIntegerField(default=5, help_text='Niveau de rappel maximum pour utiliser ce template', verbose_name='Niveau maximum')),
                ('ordre_affichage', models.PositiveIntegerField(default=10, help_text='Ordre dans la liste des templates', verbose_name="Ordre d'affichage")),
                ('variables_supplementaires', models.JSONField(blank=True, default=dict, help_text='Variables personnalisées pour ce template', verbose_name='Variables supplémentaires')),
            ],
            options={
                'verbose_name': 'Template de rappel',
                'verbose_name_plural': 'Templates de rappels',
                'ordering': ['type_template', 'ordre_affichage', 'nom'],
                'unique_together': {('nom', 'type_template', 'type_rappel', 'langue')},
            },
        ),
    ]
