# Generated by Django 5.1.8 on 2025-05-24 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0005_rappeltemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rappel',
            name='erreurs_validation',
            field=models.JSONField(blank=True, default=list, help_text='Liste des erreurs de validation détectées', verbose_name='Erreurs de validation'),
        ),
        migrations.AddField(
            model_name='rappel',
            name='template_utilise',
            field=models.ForeignKey(blank=True, help_text='Template ayant servi à générer ce rappel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotisations.rappeltemplate', verbose_name='Template utilisé'),
        ),
        migrations.AddField(
            model_name='rappel',
            name='valide_contraintes',
            field=models.BooleanField(default=True, help_text='Le rappel respecte-t-il les contraintes de son type', verbose_name='Valide selon contraintes'),
        ),
        migrations.AddField(
            model_name='rappeltemplate',
            name='derniere_utilisation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière utilisation'),
        ),
        migrations.AddField(
            model_name='rappeltemplate',
            name='nb_utilisations',
            field=models.PositiveIntegerField(default=0, help_text="Compteur d'utilisation du template", verbose_name="Nombre d'utilisations"),
        ),
        migrations.AddField(
            model_name='rappeltemplate',
            name='taux_efficacite',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage de rappels ayant obtenu une réponse', max_digits=5, null=True, verbose_name="Taux d'efficacité"),
        ),
        migrations.AddIndex(
            model_name='rappeltemplate',
            index=models.Index(fields=['type_rappel', 'type_template', 'actif'], name='cotisations_type_ra_a75d19_idx'),
        ),
        migrations.AddIndex(
            model_name='rappeltemplate',
            index=models.Index(fields=['niveau_min', 'niveau_max'], name='cotisations_niveau__757867_idx'),
        ),
        migrations.AddIndex(
            model_name='rappeltemplate',
            index=models.Index(fields=['langue', 'actif'], name='cotisations_langue_95df70_idx'),
        ),
    ]
