# Generated by Django 5.1.8 on 2025-11-16 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_log'),
        ('membres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membre',
            options={'ordering': ['date_adhesion'], 'verbose_name': 'Membre', 'verbose_name_plural': 'Membres'},
        ),
        migrations.RemoveIndex(
            model_name='membre',
            name='membres_mem_nom_849d64_idx',
        ),
        migrations.RemoveIndex(
            model_name='membre',
            name='membres_mem_email_675e02_idx',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='email',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='telephone',
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['statut'], name='membres_mem_statut__bc4f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['utilisateur'], name='membres_mem_utilisa_87b74a_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['deleted_at'], name='membres_mem_deleted_af632c_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['created_at'], name='membres_mem_created_761a87_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['updated_at'], name='membres_mem_updated_ab79c8_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['deleted_at', 'date_adhesion'], name='membres_mem_deleted_e6c5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['deleted_at', 'statut'], name='membres_mem_deleted_22b66c_idx'),
        ),
    ]
