# Generated by Django 5.1.8 on 2025-07-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisation',
            name='evenement_id',
            field=models.IntegerField(blank=True, help_text="ID de l'événement si cette cotisation est liée à un événement", null=True, verbose_name='ID Événement lié'),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='inscription_evenement_id',
            field=models.IntegerField(blank=True, help_text="ID de l'inscription à l'événement liée à cette cotisation", null=True, verbose_name='ID Inscription Événement'),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='type_cotisation',
            field=models.CharField(choices=[('adhesion', 'Adhésion'), ('cotisation', 'Cotisation'), ('evenement', 'Événement'), ('autre', 'Autre')], default='cotisation', max_length=20, verbose_name='Type de cotisation'),
        ),
    ]
