# Generated by Django 5.1.8 on 2025-05-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0002_rappel_date_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cotisation', 'Cotisation'), ('paiement', 'Paiement')], max_length=10)),
                ('reference_id', models.IntegerField()),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression')], max_length=12)),
                ('details', models.JSONField(blank=True, null=True)),
                ('utilisateur_id', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historique de transaction',
                'verbose_name_plural': 'Historique des transactions',
                'db_table': 'historique_transactions',
            },
        ),
    ]
