# Generated by Django 5.1.8 on 2025-05-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_email_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_temporary',
            field=models.BooleanField(default=False, help_text='Indique si le mot de passe est temporaire et doit être changé', verbose_name='Mot de passe temporaire'),
        ),
    ]
