# Generated by Django 5.1.8 on 2025-11-18 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type_entite', models.CharField(choices=[('global', 'Global'), ('membre', 'Membre'), ('cotisation', 'Cotisation'), ('paiement', 'Paiement'), ('evenement', 'Événement')], default='global', max_length=20, verbose_name="Type d'entité")),
            ],
            options={
                'verbose_name': 'Statut',
                'verbose_name_plural': 'Statuts',
                'ordering': ['type_entite', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Type d'action effectuée", max_length=100)),
                ('details', models.JSONField(blank=True, default=dict, help_text="Détails de l'action en JSON")),
                ('adresse_ip', models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'utilisateur", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de l'action")),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['utilisateur'], name='core_log_utilisa_730e30_idx'), models.Index(fields=['action'], name='core_log_action_77bbd8_idx'), models.Index(fields=['created_at'], name='core_log_created_0ca9f7_idx')],
            },
        ),
    ]
