# Generated by Django 5.1.8 on 2025-07-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_statut_options_statut_type_entite'),
        ('core', '0003_add_log_model'),
    ]

    operations = [
    ]
