# Generated by Django 5.1.8 on 2025-07-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20250718_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
