# Generated by Django 5.1.8 on 2025-05-22 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0003_historiquetransaction'),
        ('membres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rappel',
            name='cotisations_membre__73b8d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='rappel',
            name='cotisations_cotisat_fdf99a_idx',
        ),
        migrations.RemoveField(
            model_name='rappel',
            name='date_creation',
        ),
        migrations.AlterField(
            model_name='rappel',
            name='contenu',
            field=models.TextField(default='Rappel de cotisation - Veuillez procéder au règlement de votre cotisation.', help_text='Message à envoyer au membre', verbose_name='Contenu du rappel'),
        ),
        migrations.AlterField(
            model_name='rappel',
            name='cotisation',
            field=models.ForeignKey(help_text='Cotisation concernée par le rappel', on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='cotisations.cotisation', verbose_name='Cotisation'),
        ),
        migrations.AlterField(
            model_name='rappel',
            name='cree_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé le rappel', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='rappel',
            name='date_envoi',
            field=models.DateTimeField(help_text="Date et heure d'envoi du rappel", verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name='rappel',
            name='etat',
            field=models.CharField(choices=[('planifie', 'Planifié'), ('envoye', 'Envoyé'), ('echoue', 'Échoué'), ('lu', 'Lu')], default='planifie', help_text='État actuel du rappel', max_length=20, verbose_name='État'),
        ),
        migrations.AlterField(
            model_name='rappel',
            name='membre',
            field=models.ForeignKey(help_text='Membre destinataire du rappel', on_delete=django.db.models.deletion.CASCADE, to='membres.membre', verbose_name='Membre'),
        ),
        migrations.AlterField(
            model_name='rappel',
            name='niveau',
            field=models.PositiveIntegerField(default=1, help_text="Niveau d'urgence du rappel (1: Premier rappel, 2: Relance, etc.)", verbose_name='Niveau de rappel'),
        ),
        migrations.AlterField(
            model_name='rappel',
            name='resultat',
            field=models.TextField(blank=True, help_text="Résultat de l'envoi (erreur, accusé de réception, etc.)", null=True, verbose_name='Résultat'),
        ),
        migrations.AlterField(
            model_name='rappel',
            name='type_rappel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('courrier', 'Courrier'), ('appel', 'Appel téléphonique')], default='email', help_text="Mode d'envoi du rappel", max_length=20, verbose_name='Type de rappel'),
        ),
        migrations.AddIndex(
            model_name='rappel',
            index=models.Index(fields=['membre', 'cotisation'], name='cotisations_membre__281d0f_idx'),
        ),
    ]
