# Generated by Django 5.1.8 on 2025-07-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0002_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
